export const CONFIG = {
  API_BASE_URL: process.env.NEXT_PUBLIC_BACK_URL,
  APP_BASE_URL: process.env.NEXT_PUBLIC_FRONT_URL,
  APP_COOKIE_DOMAIN: process.env.NEXT_PUBLIC_COOKIE_DOMAIN,
  APP_GTM: process.env.NEXT_PUBLIC_GTM,
};
